FROM guacamole/guacamole

COPY guacamole-auth-quickconnect-1.3.0/guacamole-auth-quickconnect-1.3.0.jar /root/.guacamole/extensions/
COPY guacamole-auth-jwt-1.3.0.jar /root/.guacamole/extensions/
COPY libs/* /root/.guacamole/lib/
